bot:
  parse_mode: "HTML"

database:
    driver: "postgresql+asyncpg"

logger:
  sink: "subscription-bot.log"
  format: "{time}\t|\t{level}\t|\t{message}"
  level: "DEBUG"
  rotation: "10MB"
  compression: "zip"