version: "3.8"


services:
  db:
    image: postgres:16
    container_name: subscription-bot-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    command: -p ${DB_PORT}
    expose:
      - 5432
    volumes:
      - ./.databases/postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
    image: onepantsu/subscription-bot:latest
    container_name: subscription-bot
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "wait-for-it --timeout=30 db:${DB_PORT} \
             -- alembic upgrade head && python3 run.py"