name: Deploy

on:
  push:
    branches: [ main ]

env:
  GIT_URL: https://github.com/ONEPANTSU/subscription-bot.git
  WORKING_DIR: subscription-bot

  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_USER: ${{ secrets.SERVER_USERNAME }}
  SERVER_PATH: /home/${{ secrets.SERVER_USERNAME }}

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Deploy to the Server
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-agent bash -c "\
            ssh-add ../private.key && \
            ssh -o StrictHostKeyChecking=no -tt ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} -p ${{ env.SERVER_PORT }} '\
              { cd ${{ env.SERVER_PATH }}/${{ env.WORKING_DIR }} || \
              cd ${{ env.SERVER_PATH }} && \
              git clone ${{ env.GIT_URL }}; } && \
              cd ${{ env.WORKING_DIR }}; \
              echo \"$ENV\" > .env && \
              docker-compose down && \
              git pull && \
              docker-compose up -d; \
            exit'"

        shell: bash
        env:
          ENV: ${{ secrets.ENV }}
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
